"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require('dotenv').config();
const defaults = {
    REDIS_URL: '',
    DATABASE_URL: '',
    YOUTUBE_API_KEY: '',
    NODE_ENV: '',
    FIREBASE_ADMIN_SDK_CONFIG: '',
    FIREBASE_DATABASE_URL: '',
    STRIPE_SECRET_KEY: '',
    VBROWSER_SESSION_SECONDS: 10800,
    VBROWSER_SESSION_SECONDS_LARGE: 43200,
    VM_POOL_BUFFER: 0,
    VM_POOL_BUFFER_LARGE: 0,
    VM_POOL_BUFFER_FLEX: 0,
    VM_POOL_BUFFER_FLEX_LARGE: 0,
    VM_POOL_LIMIT: 0,
    VM_POOL_LIMIT_LARGE: 0,
    VM_POOL_MIN_SIZE: 0,
    VM_POOL_MIN_SIZE_LARGE: 0,
    VBROWSER_TAG: '',
    DO_TOKEN: '',
    DO_GATEWAY: '',
    HETZNER_TOKEN: '',
    HETZNER_GATEWAY: '',
    HETZNER_GATEWAY_US: '',
    HETZNER_NETWORKS: '',
    HETZNER_NETWORKS_US: '',
    HETZNER_SSH_KEYS: '',
    HETZNER_IMAGE: '',
    SCW_SECRET_KEY: '',
    SCW_ORGANIZATION_ID: '',
    SCW_GATEWAY: '',
    DOCKER_VM_HOST: '',
    DOCKER_VM_HOST_SSH_USER: '',
    DOCKER_VM_HOST_SSH_KEY_BASE64: '',
    RECAPTCHA_SECRET_KEY: '',
    HTTPS: '',
    SSL_KEY_FILE: '',
    SSL_CRT_FILE: '',
    PORT: 8080,
    HOST: '0.0.0.0',
    STATS_KEY: '',
    CUSTOM_SETTINGS_HOSTNAME: '',
    MEDIA_PATH: '',
    STREAM_PATH: '',
    KV_KEY: '',
    ROOM_CAPACITY: 0,
    ROOM_CAPACITY_SUB: 0,
    BUILD_DIRECTORY: 'build',
    VM_MANAGER_ID: 'Docker',
    VM_MIN_UPTIME_MINUTES: 0,
    SHARD: undefined,
    SUBSCRIBER_ROOM_LIMIT: 20, // The maximum number of rooms a subscriber can have
};
exports.default = Object.assign(Object.assign({}, defaults), process.env);
